---
- name: config | configure docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 'u=rw,go=r'
    backup: yes
  when: docker_daemon_config and docker_daemon_config is iterable and docker_daemon_config | length > 0
  notify:
    - restart docker

- name: config | add users to docker group
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  loop: "{{ docker_allowed_user }}"

- name: config | log into docker registry private servers
  docker_login:
    registry_url: "{{ item.host | default(omit) }}"
    username: "{{ item.user }}"
    password: "{{ item.password }}"
  become: true
  become_user: "{{ item.owner }}"
  loop: "{{ docker_registry_auth }}"
