---
- name: remove old pip docker-compose dependencies
  pip:
    executable: "{{ python_2_pip_bin|default('pip') }}"
    name: "{{ item }}"
    state: "absent"
  with_items:
    - dockerpty
    - docker-pycreds
    - docker
    - docker-py

- name: install docker compose (pip)
  pip:
    executable: "{{ python_2_pip_bin|default('pip') }}"
    name: docker-compose
    version: "{{ docker_compose_version|default(omit) if docker_compose_version != 'latest' and docker_compose_version != '' else omit }}"
    state: "{{ docker_compose_state }}"
