---
- include: install_docker_compose_bin.yml
  when: not docker_compose_by_pip

- include: install_docker_compose_pip.yml
  when: docker_compose_by_pip

- name: get docker compose version
  shell: "docker-compose version --short"
  register: docker_compose_current_result
  ignore_errors: yes

- name: set docker-compose version fact
  set_fact:
      docker_compose_current_version: "{{ docker_compose_current_result.stdout|default('') }}"
  register: docker_compose_version_fact_result

- name: download docker compose bash completion script
  get_url:
    url: 'https://raw.githubusercontent.com/docker/compose/{{ docker_compose_current_version }}/contrib/completion/bash/docker-compose'
    dest: /etc/bash_completion.d/docker-compose
    mode: 0644
  when: docker_compose_current_version is defined and docker_compose_current_version != ''
