---
- include: debian_install_docker.yml
  when: ansible_os_family == 'Debian'
  tags:
  - docker

- include: install_docker_compose.yml
  tags:
  - docker
  - docker-compose

- include: install_docker_machine.yml
  when: docker_machine_install|bool and not docker_machine_gitlab|bool
  tags:
  - docker
  - docker-machine

- include: install_docker_machine_gitlab.yml
  when: docker_machine_install|bool and docker_machine_gitlab|bool
  tags:
  - docker
  - docker-machine

- include: config.yml
  tags:
  - docker
  - docker-config
